### ISSUE TITLE
Feature request: Any chance you could tweak this to work on Linux?

### ISSUE THREAD

**Issue by aia832003** [leyanlo/electron-pandora#3]
I know it's not the most popular platform, but with the similarities in structure to Linux, would this be possible? Thanks.

**Comment by M1kep** [comment]
Are you still interested in this @aia832003 ? I did some preliminary testing and should be able to fork or send a pull request if you'd like.

**Comment by aia832003** [comment]
That would be great! I'd be happy to attempt a test run.

**Comment by M1kep** [comment]
@aia832003 I've added the linux support. I have a release on my fork, but in theory there should be a release on here once merged.
